### ISSUE TITLE
请问这是跟人项目吗，现在的成熟度和稳定度怎么样

### ISSUE THREAD

**Issue by ydaydayup** [web-widget/web-widget#557]
请问这是跟人项目吗，现在的成熟度和稳定度怎么样

**Comment by aui** [comment]
目前它还还未进入到稳定状态，例如文档与相关配套设施还欠缺。目前这个框架驱动如下产品：

- https://www.gaoding.com
- https://www.insmind.com

如果有疑问欢迎交流细节～
